

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black
    name: black
- repo: https://github.com/cisagov/pre-commit-packer
  rev: v0.3.1
  hooks:
  - id: packer_fmt
