boot_command      = ["<tab><wait30s> inst.text inst.ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/ks-9.cfg <enter><wait>"]
boot_command_hv   = ["c  setparams 'kickstart' <enter> linuxefi /images/pxeboot/vmlinuz inst.stage2=hd:LABEL=OL-9-4-0-BaseOS-x86_64 inst.ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/ks-9.cfg<enter> initrdefi /images/pxeboot/initrd.img<enter> boot<enter>"]
boot_wait         = "5s"
box_basename      = "oracle-9.0"
build_directory   = "../builds"
cpus              = "2"
disk_size         = "65536"
headless          = false
http_directory    = "./http"
hyperv_generation = "1"
hyperv_switch     = "default"
iso_checksum      = "77034a4945474cb7c77820bd299cac9a557b8a298a5810c31d63ce404ad13c5e"
iso_path          = "../../ISOs/Oracle/OracleLinux-R9-U4-x86_64-dvd.iso"
iso_url           = "https://yum.oracle.com/ISOS/OracleLinux/OL9/u4/x86_64/OracleLinux-R9-U4-x86_64-dvd.iso"
memory            = "1024"
name              = "oracle-9.4"
ssh_password      = "vagrant"
ssh_timeout       = "10000s"
ssh_username      = "vagrant"
switch_name          = "Default Switch"
vlan_id              = ""
template          = "oracle-9.4-x86_64"
version           = "TIMESTAMP"
